AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance for Job System - Production Grade (Optional)'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Environment name (dev, staging, prod)
  
  ProjectName:
    Type: String
    Default: jobsys
    Description: Project name for resource naming

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t2.micro, t3.micro, t3.small, t3.medium]
    Description: EC2 instance type

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair name for SSH access

  AllowedSSHIP:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed for SSH access (use your IP for security)
    AllowedPattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'

  APIPort:
    Type: Number
    Default: 8080
    Description: Port for API service
    MinValue: 1
    MaxValue: 65535

  EC2InstanceProfileName:
    Type: String
    Description: EC2 instance profile name (from IAM stack)

  APIRepositoryURI:
    Type: String
    Description: ECR repository URI for API (from ECR stack)

  WorkerRepositoryURI:
    Type: String
    Description: ECR repository URI for Worker (from ECR stack)

  TableName:
    Type: String
    Description: DynamoDB table name (from DynamoDB stack)

  JobsQueueUrl:
    Type: String
    Description: SQS queue URL (from SQS stack)

  # Get latest Amazon Linux 2 AMI (SSM parameter lookup)
  LatestAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Configuration
        Parameters:
          - Environment
          - ProjectName
      - Label:
          default: Instance Settings
        Parameters:
          - InstanceType
          - KeyPairName
          - AllowedSSHIP
          - APIPort
      - Label:
          default: References (from other stacks)
        Parameters:
          - EC2InstanceProfileName
          - APIRepositoryURI
          - WorkerRepositoryURI
          - TableName
          - JobsQueueUrl

Resources:
  # VPC (using default VPC)
  # Note: In production, you'd create a custom VPC, but for simplicity we use default

  # Security Group
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-ec2-sg-${Environment}'
      GroupDescription: Security group for Job System EC2 instance
      SecurityGroupIngress:
        # SSH Access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHIP
          Description: SSH access
        # API Access
        - IpProtocol: tcp
          FromPort: !Ref APIPort
          ToPort: !Ref APIPort
          CidrIp: 0.0.0.0/0
          Description: API service access
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-EC2-SG-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAMI
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref EC2InstanceProfileName
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y docker
          systemctl start docker
          systemctl enable docker
          usermod -a -G docker ec2-user
          
          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          # Create application directory
          mkdir -p /opt/${ProjectName}
          cd /opt/${ProjectName}
          
          # Login to ECR
          aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          
          # Note: docker-compose.yml and image pulling will be done manually
          # or via a deployment script
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-EC2-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${ProjectName}-${Environment}-InstanceId'

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PublicIP'

  SecurityGroupId:
    Description: Security group ID
    Value: !Ref EC2SecurityGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-SecurityGroupId'

  APIEndpoint:
    Description: API endpoint URL
    Value: !Sub 'http://${EC2Instance.PublicIp}:${APIPort}'
    Export:
      Name: !Sub '${ProjectName}-${Environment}-APIEndpoint'

